### ISSUE TITLE
"Click to convert" Not Working!

### ISSUE THREAD

**Issue by Annu33202** [digimezzo/vitomu#1]
I've just installed `version 2.0.0` and I was trying to convert video from youtube. It's detecting the link but conversion still not working.

**Comment by digimezzo** [comment]
@Annu33202 Do you have this problem with all youtube video's or just a specific video? Would you mind pasting the youtube link here so I can try it out?

Also, what happens when you click on "Click to convert"?
Is this on Windows or Linux?

**Comment by digimezzo** [comment]
@Annu33202 Version 2.0.1 was just released. It might solve your issue.

**Comment by Annu33202** [comment]
> @Annu33202 Do you have this problem with all youtube video's or just a specific video? Would you mind pasting the youtube link here so I can try it out?
> 
> Also, what happens when you click on "Click to convert"?
> Is this on Windows or Linux?

I'm using window and I tried on just one video on youtube here is the [link](https://www.youtube.com/watch?v=h7gyJRWrjbg&list=LLACvVMPzHRMwX8sEW-bPxGQ&index=5&t=0s)
Nothing happened, on hovering, it tells "Click to convert" but after clicking nothing happened.

**Comment by Annu33202** [comment]
> @Annu33202 Version 2.0.1 was just released. It might solve your issue.

After Installing `version 2.0.1` "Click to convert" option worked and it showed the error message of "FFmpeg missing".
So I installed the FFmpeg through this [guide](https://www.youtube.com/watch?v=f_OOhBniSu8) for windows, and now it's working like a charm.
Thank you for the amazing software.

**Comment by digimezzo** [comment]
@Annu33202 Thanks for letting me know. I'll improve this even further for the next version.
