### ISSUE TITLE
"Conversion failed" error

### ISSUE THREAD

**Issue by Rigel772** [digimezzo/vitomu#26]
On Manjaro  and Vitomu 2.0.3 I am only getting "Conversion failed" with any link I try from YT...
Eg:
https://www.youtube.com/watch?v=0BtLnArPCuY

**Comment by digimezzo** [comment]
@Rigel772 Thank you for you bug report. I'll look into it ASAP. Youtube has probably changed its API again.

**Comment by Rigel772** [comment]
Should not it stay open until fixed? For others to be aware...

**Comment by digimezzo** [comment]
@Rigel772 No. Issues are closed as soon as it's fixed in code. The milestone in which the fix will be available is displayed in the right pane of this issue. The fix will be in version 2.0.4. It will be released very soon.
