### ISSUE TITLE
Sometime don't see copied link from Youtube

### ISSUE THREAD

**Issue by PrzemekSkw** [digimezzo/vitomu#30]
Hello, Yesterday I click on Youtube movie and click `copy movie url` and Vitomu see that link. Today Vitomu don't see link. I must copy link from browser url bar. But that way Vitomu failed.

I have version 2.0.3 on Ubuntu Budgie installed with apt install.

Regards,
Przemek

**Comment by digimezzo** [comment]
Fixed in commit 830ca156731b79ad511d543f02736d740de0d4e7
